#!/bin/bash

export NCCL_DEBUG_SUBSYS=INIT,GRAPH
export CUBLAS_WORKSPACE_CONFIG=:4096:8
export NCCL_SOCKET_IFNAME=100gp1
export NCCL_IB_HCA=mlx5
export NCCL_ALGO=Ring
export NCCL_PROTO=Simple
export NCCL_DEBUG=INFO
unset NCCL_MAX_NCHANNELS
unset NCCL_MIN_NCHANNELS
unset NCCL_IB_DISABLE
unset NCCL_NET_PLUGIN

